version: "3.9"

services:
  db:
    restart: always
    image: postgres:alpine
    ports:
      - 5433:5432
    volumes:
      - database_data:/var/lib/postgresql/data:delegated
    env_file:
      - docker/environments/db.env

  redis:
    restart: always
    image: redis:5-alpine
    ports:
      - 6380:6379
    volumes:
      - "redis_data:/data"

volumes:
  database_data:
  redis_data:
